INSERT INTO faixa VALUES(0, Violin Concerto No. 1 in B-Flat Major, K. 207: I. Allegro moderato, 0, __, 6.37, __, __)
INSERT INTO faixa VALUES(1, Violin Concerto No. 1 in B-Flat Major, K. 207: II. Adagio, 1, __, 6.8, __, __)
INSERT INTO faixa VALUES(2, Violin Concerto No. 1 in B-Flat Major, K. 207: III. Presto, 2, __, 5.78, __, __)
INSERT INTO faixa VALUES(3, Violin Concerto No. 2 in D Major, K. 211: I. Allegro moderato, 3, __, 7.55, __, __)
INSERT INTO faixa VALUES(4, Violin Concerto No. 2 in D Major, K. 211: II. Andante, 4, __, 5.58, __, __)
INSERT INTO faixa VALUES(5, Violin Concerto No. 2 in D Major, K. 211: III. Allegro, 5, __, 3.6, __, __)
INSERT INTO faixa VALUES(6, Violin Concerto No. 3 in G Major, K. 216: I. Allegro, 6, __, 7.6, __, __)
INSERT INTO faixa VALUES(7, Violin Concerto No. 3 in G Major, K. 216: II. Adagio, 7, __, 6.32, __, __)
INSERT INTO faixa VALUES(8, Violin Concerto No. 3 in G Major, K. 216: III. Rondeau (Allegro), 8, __, 6.27, __, __)
INSERT INTO faixa VALUES(9, Violin Concerto No. 4 in D Major, K. 218: I. Allegro, 9, __, 8.33, __, __)
INSERT INTO faixa VALUES(10, Violin Concerto No. 4 in D Major, K. 218: II. Andante cantabile, 10, __, 8.8, __, __)
INSERT INTO faixa VALUES(11, Violin Concerto No. 4 in D Major, K. 218: III. Rondeau. Andante grazioso - Allegro ma non troppo, 11, __, 6.58, __, __)
INSERT INTO faixa VALUES(12, Violin Concerto No. 5 in A Major, K. 219: I. Allegro aperto, 12, __, 10.12, __, __)
INSERT INTO faixa VALUES(13, Violin Concerto No. 5 in A Major, K. 219: II. Adagio, 13, __, 12.68, __, __)
INSERT INTO faixa VALUES(14, Violin Concerto No. 5 in A Major, K. 219: III Rondeau, 14, __, 9.1, __, __)
