INSERT INTO faixa VALUES(0, Piano Sonata No. 9 in D Major, K. 311: I. Allegro con spirito, 0, __, 4.4, __, __)
INSERT INTO faixa VALUES(1, Piano Sonata No. 9 in D Major, K. 311: II. Andante con expressione, 1, __, 6.15, __, __)
INSERT INTO faixa VALUES(2, Piano Sonata No. 9 in D Major, K. 311: III. Rondo, 2, __, 5.97, __, __)
INSERT INTO faixa VALUES(3, Piano Sonata No. 4 in E-Flat Major, K. 282: I. Adagio, 3, __, 6.7, __, __)
INSERT INTO faixa VALUES(4, Piano Sonata No. 4 in E-Flat Major, K. 282: II. Menuettos I & II, 4, __, 3.85, __, __)
INSERT INTO faixa VALUES(5, Piano Sonata No. 4 in E-Flat Major, K. 282: III. Allegro, 5, __, 2.9, __, __)
INSERT INTO faixa VALUES(6, Piano Sonata No. 1 in C Major, K. 279: I. Allegro, 6, __, 4.68, __, __)
INSERT INTO faixa VALUES(7, Piano Sonata No. 1 in C Major, K. 279: II. Andante, 7, __, 5.57, __, __)
INSERT INTO faixa VALUES(8, Piano Sonata No. 1 in C Major, K. 279: III. Allegro, 8, __, 3.03, __, __)
INSERT INTO faixa VALUES(9, Piano Sonata No. 6 in D Major, K. 284 "Dürnitz": I. Allegro, 9, __, 5.0, __, __)
INSERT INTO faixa VALUES(10, Piano Sonata No. 6 in D Major, K. 284 "Dürnitz": II. Rondeau en polonaise, 10, __, 4.63, __, __)
INSERT INTO faixa VALUES(11, Piano Sonata No. 6 in D Major, K. 284 "Dürnitz": III. Tema con variazione, 11, __, 15.47, __, __)
